import { keyframes, style } from '@vanilla-extract/css';
import { vars } from '../theme.css';

export const root = style({ display: 'flex', flexDirection: 'column', height: '100%', minHeight: 0, overflow: 'hidden', fontSize: '0.7rem', fontFamily: vars.font.body, color: vars.color.foreground });
export const body = style({ flex: 1, minHeight: 0, overflowY: 'auto', overflowX: 'hidden' });
export const toolbar = style({ display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: 6, padding: '7px 9px', flexShrink: 0, borderBottom: `1px solid ${vars.color.border}` });
export const title = style({ fontSize: '0.78rem', fontWeight: 700 });
export const badge = style({ color: vars.color.accent, border: `1px solid ${vars.color.border}`, background: vars.color.inset, borderRadius: vars.radius.sm, padding: '2px 5px', fontSize: '0.62rem' });
export const refresh = style({ display: 'inline-flex', justifyContent: 'center', alignItems: 'center', marginLeft: 'auto', width: 25, height: 25, border: `1px solid ${vars.color.border}`, borderRadius: vars.radius.sm, background: 'transparent', color: vars.color.mutedForeground, cursor: 'pointer', ':hover': { background: vars.color.muted, color: vars.color.foreground }, ':disabled': { opacity: 0.5, cursor: 'wait' }, ':focus-visible': { outline: `2px solid ${vars.color.accent}` } });
const spin = keyframes({ to: { transform: 'rotate(360deg)' } });
export const spinning = style({ animation: `${spin} 1s linear infinite` });
export const note = style({ margin: 0, padding: '5px 9px', fontSize: '0.64rem', color: vars.color.mutedForeground, lineHeight: 1.6, overflowWrap: 'anywhere' });
export const sourceNote = style([note, { paddingTop: 0, fontVariantNumeric: 'tabular-nums' }]);
export const notice = style([note, { color: vars.color.accent, background: vars.color.accentDim }]);
export const warning = style([note, { color: vars.color.amber, background: vars.color.inset }]);
export const heading = style({ display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'center', gap: 5, padding: '7px 9px', margin: 0, fontSize: '0.73rem', fontWeight: 600, background: vars.color.inset, borderTop: `1px solid ${vars.color.border}`, borderBottom: `1px solid ${vars.color.border}` });
export const sides = style({ display: 'flex', flexWrap: 'wrap', gap: 0 });
export const sidePanel = style({ flex: '1 1 310px', minWidth: 0, width: '100%' });
export const sideHeading = style({ margin: 0, display: 'flex', justifyContent: 'space-between', gap: 5, padding: '6px 9px', fontSize: '0.72rem', background: vars.color.panelRaised, borderBottom: `1px solid ${vars.color.border}` });
export const long = style({ color: vars.color.up, fontWeight: 600 });
export const short = style({ color: vars.color.down, fontWeight: 600 });
export const stock = style({ borderBottom: `1px solid ${vars.color.border}` });
export const row = style({ display: 'grid', gridTemplateColumns: '21px minmax(0,1fr) auto', width: '100%', minWidth: 0, gap: '3px 6px', textAlign: 'left', padding: '7px 9px 4px', background: 'transparent', color: vars.color.foreground, border: 0, cursor: 'pointer', ':hover': { background: vars.color.muted }, ':focus-visible': { outline: `2px solid ${vars.color.accent}`, outlineOffset: -2 } });
export const rank = style({ borderRadius: vars.radius.sm, alignSelf: 'start', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', minHeight: 20, background: vars.color.muted, fontVariantNumeric: 'tabular-nums', fontSize: '0.65rem' });
export const identity = style({ display: 'flex', flexDirection: 'column', gap: 2, minWidth: 0 });
export const name = style({ fontSize: '0.72rem', fontWeight: 600, overflowWrap: 'anywhere' });
export const info = style({ fontWeight: 400, fontSize: '0.62rem', lineHeight: 1.5, color: vars.color.mutedForeground, overflowWrap: 'anywhere' });
export const numbers = style({ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 2, fontVariantNumeric: 'tabular-nums', fontFamily: vars.font.mono, fontSize: '0.68rem' });
export const metrics = style({ gridColumn: '2 / -1', display: 'flex', flexWrap: 'wrap', gap: '2px 9px', color: vars.color.mutedForeground, fontSize: '0.61rem', fontVariantNumeric: 'tabular-nums', lineHeight: 1.6 });
export const source = style([info, { gridColumn: '2 / -1', fontSize: '0.59rem', fontVariantNumeric: 'tabular-nums' }]);
export const rowDetails = style({ padding: '0 9px 5px 36px', color: vars.color.mutedForeground, fontSize: '0.61rem' });
export const detailsSummary = style({ cursor: 'pointer', lineHeight: 1.6, ':hover': { color: vars.color.foreground } });
export const detailMetrics = style({ display: 'flex', flexWrap: 'wrap', gap: '3px 9px', paddingTop: 4, fontVariantNumeric: 'tabular-nums' });
export const reasons = style({ margin: '4px 0 0', paddingLeft: 15, lineHeight: 1.7, overflowWrap: 'anywhere' });
export const empty = style({ margin: 0, padding: '10px 9px', fontSize: '0.65rem', lineHeight: 1.6, color: vars.color.mutedForeground, overflowWrap: 'anywhere' });
export const excluded = style({ marginTop: 3 });
export const excludedRow = style({ display: 'flex', flexDirection: 'column', gap: 3, padding: '7px 9px', borderBottom: `1px solid ${vars.color.border}` });
