import { style } from '@vanilla-extract/css';
import { vars } from '../theme.css';

export const root = style({ display: 'flex', flexDirection: 'column', flex: 1, minHeight: 0, minWidth: 0, overflow: 'hidden', color: vars.color.foreground, background: vars.color.panel, fontFamily: vars.font.body, fontSize: '0.7rem' });
export const body = style({ flex: 1, minHeight: 0, minWidth: 0, overflowY: 'auto', overflowX: 'hidden', padding: '0 9px 12px' });
export const toolbar = style({ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: 6, padding: '7px 9px', borderBottom: `1px solid ${vars.color.border}`, flexShrink: 0 });
export const title = style({ margin: 0, fontSize: '0.79rem', fontWeight: 700 });
export const badge = style({ fontSize: '0.63rem', color: vars.color.accent, background: vars.color.accentDim, borderRadius: vars.radius.sm, padding: '3px 5px' });
export const actions = style({ display: 'flex', flexWrap: 'wrap', gap: 6, alignItems: 'center', margin: '7px 0' });
export const button = style({ border: `1px solid ${vars.color.borderBright}`, background: vars.color.inset, color: vars.color.foreground, font: 'inherit', borderRadius: vars.radius.sm, padding: '5px 8px', minHeight: 29, cursor: 'pointer', ':hover': { background: vars.color.muted }, ':disabled': { opacity: 0.5, cursor: 'not-allowed' }, ':focus-visible': { outline: `2px solid ${vars.color.accent}` } });
export const recordButton = style([button, { marginLeft: 'auto' }]);
export const note = style({ margin: '7px 0', color: vars.color.mutedForeground, fontSize: '0.65rem', lineHeight: 1.7, overflowWrap: 'anywhere' });
export const warning = style([note, { color: vars.color.amber, background: vars.color.inset, borderLeft: `2px solid ${vars.color.amber}`, padding: '6px 8px' }]);
export const notice = style([note, { color: vars.color.accent, background: vars.color.accentDim, padding: '7px 8px' }]);
export const section = style({ borderTop: `1px solid ${vars.color.border}`, marginTop: 10, paddingTop: 8, minWidth: 0 });
export const heading = style({ fontWeight: 600, fontSize: '0.74rem', margin: '0 0 7px', lineHeight: 1.6 });
export const field = style({ display: 'flex', flexDirection: 'column', minWidth: 0, gap: 4, color: vars.color.mutedForeground, fontSize: '0.64rem', lineHeight: 1.5 });
export const input = style({ width: '100%', minWidth: 0, boxSizing: 'border-box', border: `1px solid ${vars.color.borderBright}`, borderRadius: vars.radius.sm, padding: '5px 6px', color: vars.color.foreground, background: vars.color.inset, font: 'inherit', minHeight: 29, ':focus-visible': { outline: `2px solid ${vars.color.accent}` } });
export const fields = style({ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(125px, 1fr))', gap: 8 });
export const journal = style({ maxHeight: 220, overflowY: 'auto', border: `1px solid ${vars.color.border}`, borderRadius: vars.radius.sm });
export const journalRow = style({ display: 'flex', gap: 7, alignItems: 'flex-start', padding: '7px 6px', borderBottom: `1px solid ${vars.color.border}`, cursor: 'pointer', overflowWrap: 'anywhere' });
export const journalText = style({ display: 'flex', flexDirection: 'column', gap: 2, minWidth: 0, fontVariantNumeric: 'tabular-nums' });
export const tiny = style({ color: vars.color.mutedForeground, fontSize: '0.6rem', lineHeight: 1.6, overflowWrap: 'anywhere' });
export const slider = style({ width: '100%', minWidth: 0, margin: '7px 0', accentColor: vars.color.accent });
export const cards = style({ display: 'flex', flexWrap: 'wrap', gap: 8 });
export const card = style({ flex: '1 1 250px', minWidth: 0, background: vars.color.inset, border: `1px solid ${vars.color.border}`, borderRadius: vars.radius.sm, padding: 8 });
export const metrics = style({ display: 'grid', gridTemplateColumns: 'minmax(0,1fr) auto', gap: '5px 8px', margin: '6px 0', lineHeight: 1.6, fontVariantNumeric: 'tabular-nums' });
export const term = style({ margin: 0, color: vars.color.mutedForeground, overflowWrap: 'anywhere' });
export const value = style({ margin: 0, textAlign: 'right' });
export const details = style({ borderTop: `1px solid ${vars.color.border}`, paddingTop: 7, marginTop: 7 });
export const summary = style({ cursor: 'pointer', lineHeight: 1.7, fontWeight: 600 });
export const row = style({ padding: '7px 0', borderBottom: `1px solid ${vars.color.border}`, minWidth: 0, overflowWrap: 'anywhere' });
export const stockButton = style([button, { border: 0, padding: '2px 0', background: 'transparent', minHeight: 24, textAlign: 'left', fontWeight: 600 }]);
export const reasons = style({ margin: '4px 0 0', paddingLeft: 17, lineHeight: 1.7, color: vars.color.mutedForeground, fontSize: '0.63rem', overflowWrap: 'anywhere' });
export const status = style({ lineHeight: 1.7, fontSize: '0.65rem', marginTop: 5, overflowWrap: 'anywhere' });
export const difference = style({ color: vars.color.amber, lineHeight: 1.7, fontSize: '0.65rem', overflowWrap: 'anywhere' });
export const file = style({ display: 'block', width: '100%', minWidth: 0, fontSize: '0.64rem', color: vars.color.mutedForeground, marginTop: 4 });
